version: '2'

services:

  nginx:
    image: nginx:latest
    ports:
      - 8025:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php

  php:
    build: ./docker/php/
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
        - database

    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  database:
        image: mysql:5.7
        environment:
          - "MYSQL_ROOT_PASSWORD=secret"
          - "MYSQL_DATABASE=laravel_gentelella"
        volumes:
          - ${BACKUP_DATA_PATH}/mysql9:/var/lib/mysql
        ports:
          - "33099:3306"


